language: node_js
node_js:
  - 0.10
before_install: 
  - cd $TRAVIS_BUILD_DIR
  - cp config/config.sample.json config/config.json
  - cp config/credentials.sample.json config/credentials.json
install:
  - cd $TRAVIS_BUILD_DIR/
  - npm install
script:
  - cd $TRAVIS_BUILD_DIR/
  - npm run test
  - npm run lint
